/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package connect4withmachine;

public class App {
    public static void main(String[] args) {
        App app = new App();
        app.run();
    }

    void run () {
        // connect 4 
        int opc;
        do {
            menu();
            opc = Utilities.readInt();
            switch (opc) {
                case 1:
                    // player vs player
                    PlayerVsPlayer();
                    break;
                case 2:
                    // player vs pc
                    PlayerVsPC();
                    break;
            }
        } while (opc != 0);

        
    }

    void menu (){
        System.out.println("WELCOME TO CONNECT 4");
        System.out.println("Choose an option");
        System.out.println("1) Player vs Player");
        System.out.println("2) Player vs PC");
        System.out.println("0) Exit");
    }

    /**
     ************************************************************
        * PlayerVsPlayer
    ************************************************************
        */
    void PlayerVsPlayer () {
        // Player vs Player
        System.out.println("Enter player 1 name");
        String name1 = Utilities.readString();
        System.out.println("Enter player 2 name");
        String name2 = Utilities.readString();
        
        Player player1 = new Player(name1, 'X');
        Player player2 = new Player(name2, 'O');
        
        Board board = new Board();
        Game game = new Game(player1, player2, board);

        game.play();
    }

    /**
     ************************************************************
        * PlayerVsPC
    ************************************************************
        */
    void PlayerVsPC () {
        // Player vs PC
        System.out.println("Enter player name");
        String name = Utilities.readString();
        
        Player player = new Player(name, 'X');
        PC pc = new PC("PC", 'O');

        Board board = new Board();
        Game game = new Game(player, pc, board);

        game.play();
    }
}
